#!/bin/bash

# This script is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

set -e
. /etc/simplelxc
. $BIN_DIR/functions

for guest in $(get_guest_list); do
	printf "%-12s %-12s %-16s\n" "$guest" "$(get_guest_state $guest)" "$(get_guest_ip $guest)"
done
