#!/bin/bash
set -e
. /etc/simplelxc
. $BIN_DIR/functions

name=$1

if ! is_guest "$name"; then
	color_echo RED "There is no guest named '$name'"
	echo "You can see a list of existing guests by:
>>> $(get_sl_command) list $name"
	exit 1
fi

editor $LXCS_DIR/$name/config

if is_guest_running "$name"; then
	# TODO: we should change guest properties on the fly
	echo "You must restart the server if it is running, you can do it by:
>>> $(get_sl_command) restart $name"
fi
