#!/bin/bash
set -e
. /etc/simplelxc
. $BIN_DIR/functions

name=$1

export LANGUAGE=C
export LC_ALL=C
export LANG=C

if ! is_guest $name; then
	color_echo RED "There is no guest named '$name'"
	echo "You can see a list of existing guests by:
>>> $(get_sl_command) list"
	exit 1
fi

if is_guest_running $name; then
	color_echo RED "Guest '$name' is already running!"
else
	lxc-start --name $name --daemon
	#lxc-start --logpriority DEBUG --logfile /dev/tty --name $name
	color_echo GREEN "Started guest '$name'"
fi

echo "You can enter to guest '$name' by:
>>> $(get_sl_command) enter $name"
