#!/bin/bash
name=$1
. /etc/simplelxc
vi $LXCS_DIR/$name/config
# TODO: check if lxc is running first
echo "You must restart the server if it running, you can do i t by typing this:"
echo ">>> 'sudo simplelxc restart $name'"
