#!/bin/bash
from=$1
to=$2
ip=$4
. /etc/simplelxc

oldip=$(cat $LXCS_DIR/$from/rootfs/etc/hosts | awk "/$from/ {print \$1}")

cp -rap $LXCS_DIR/$from $LXCS_DIR/$to
rootfs=$LXCS_DIR/$to/rootfs
sed -i "s/$from/$to/g" $(grep -rl "$from" $rootfs/etc/ 2>/dev/null)
sed -i "s/$oldip/$ip/g" $(grep -rl "$oldip" $rootfs/etc/ 2>/dev/null)

lxc-start -d -n $to
