#!/bin/bash
set -e
. /etc/simplelxc
. $BIN_DIR/functions

name=$1

if ! is_guest "$name"; then
	color_echo RED "There is no guest: \"$name\""
	exit 1
fi

if is_guest_running "$name"; then
	color_echo RED "Guest \"$name\" is running."
fi

echo "
      Be careful, if you are not sure what you are doing you should
      use 'enter':
      >>> $(get_sl_command) enter $name
"
if yesno "Do you still want to chroot (Yes|[No])? " n; then
	chroot $LXCS_DIR/$name/rootfs
fi
