#!/bin/bash

# exit on first error
set -e

. /etc/simplelxc

# if there is no cgroup mounted
if ! grep " cgroup " /proc/mounts &>/dev/null; then
	mkdir /cgroup
	mount -t cgroup cgroup /cgroup
	echo "cgroup          /cgroup         cgroup  defaults        0       0" >> /etc/fstab
fi

# if there is no bridge
if ! brctl show | grep ^$BRIDGE_INTERFACE &>/dev/null; then
	cp /etc/network/interfaces /etc/network/interfaces.simplelxc-bak
	cat <<EOF >> /etc/network/interfaces
auto $BRIDGE_INTERFACE
iface $BRIDGE_INTERFACE inet static
	address $HOST_IP
	netmask $NETMASK
	bridge_ports none
	bridge_fd 9
	bridge_hello 2
	bridge_maxage 12
	bridge_stp off
EOF
	ifup -v $BRIDGE_INTERFACE
fi

# prepare nat
if sysctl net.ipv4.ip_forward | grep '0' &>/dev/null; then
	sed -i.simplelxc-bak "/net.ipv4.ip_forward/s/.*/net.ipv4.ip_forward=1/" /etc/sysctl.conf
	sysctl -w net.ipv4.ip_forward=1
fi

if ! iptables -L -t nat | grep $NETWORK &>/dev/null; then
	out_interface=$(ip route ls | grep ^default | sed 's/.* dev \([^ ]\+\)/\1/g')
	iptables -t nat -s $NETWORK/24 -A POSTROUTING -o $out_interface -j MASQUERADE
	iptables-save > /etc/iptables.up.rules
	cat<<-EOF > /etc/network/if-pre-up.d/iptables
	#!/bin/bash
	/sbin/iptables-restore < /etc/iptables.up.rules
	EOF
fi
