#!/bin/bash

# This script is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

# TODO: we should move this kind of functions to a file wich we import that file where needed
function show_error {
	echo -e "${0##*/}: \E[31m$1" >&2
	tput sgr0 >&2
	exit 2
}

# check root
if [[ $EUID -ne 0 ]]; then
	show_error "You must be root to run this script."
	exit 2
fi

. /etc/simplelxc

# check dependencies
if dpkg -l lxc bridge-utils debootstrap iptables iproute apt-cacher-ng | grep "No packages found" &>/dev/null; then
	show_error "Dependencies failed"
	exit 2 
fi

# check cgroup
if ! grep " cgroup " /proc/mounts &>/dev/null; then
	show_error "cgroup file system failed, not mounted"
	exit 2 
fi

# check bridge
if ! brctl show | grep ^$BRIDGE_INTERFACE &>/dev/null; then
	show_error "Bridge interface not exits"
	exit 2 
fi

if ! ifconfig $BRIDGE_INTERFACE | grep addr:$HOST_IP &>/dev/null; then
	show_error "Bridge interface not configured"
	exit 2 
fi

# prepare nat
if sysctl net.ipv4.ip_forward | grep '0' &>/dev/null; then
	show_error "IP forwarding not set"
	exit 2 
fi

if ! iptables -L -t nat | grep $NETWORK &>/dev/null; then
	show_error "NAT rules (iptables) not configured"
	exit 2 
fi

exit 0
