#!/bin/bash
. /etc/simplelxc

glist='list create copy login start stop destroy info restart config chroot'

if echo $glist | grep $1 &>/dev/null; then
	command="guest-$1"
	shift 1
else
	command="$1-$2"
	shift 2
fi

if ! test -f $BIN_DIR/$command; then
	echo "Cannot find a suitible command"
fi
exec $BIN_DIR/$command "$@"
