#!/bin/bash
set -e
. /etc/simplelxc
name=${1:-$DEFAULT_TEMPLATE}
release=${2:-$DEFAULT_TEMPLATE}

export LANGUAGE=C
export LC_ALL=C
export LANG=C

exec 3>&1 4>&2 >>/var/log/simplelxc 2>&1
echo "================================================================================"
echo "$(date +%F\ %T): Running: $0 $@"

release_dir=$DEBOOTSTRAPS_DIR/$release
if ! test -d $release_dir; then
	mkdir -p $(dirname $release_dir)
	debootstrap --variant=minbase $release $release_dir http://$HOST_IP:3142/ftp.debian.org/debian
fi

template_dir=$TEMPLATES_DIR/$name
if test -d $template_dir; then
	echo $template_dir zaten var
else
	mkdir -p $(dirname $template_dir)
fi

# cp debootstrap root to lxc ready template directory
cp -apr $release_dir $template_dir | :

echo "template-$name" > $template_dir/etc/hostname
echo -e "127.0.0.1\tlocalhost\n127.0.0.2\ttemplate-$name" > $template_dir/etc/hosts

# disable all ttys
sed -i '/getty 38400/s/\(.*\)/#\1/g' $template_dir/etc/inittab

# Fix mtab
rm -f $template_dir/etc/mtab
ln -s /proc/mounts $template_dir/etc/mtab

# configure apt-cacher-ng
echo "Acquire::http::Proxy \"http://$HOST_IP:3142/\";" > $template_dir/etc/apt/apt.conf.d/000apt-cacher-ng-proxy
echo "deb http://ftp.debian.org/debian squeeze main contrib non-free" > $template_dir/etc/apt/sources.list

echo nameserver 8.8.8.8 > $template_dir/etc/resolv.conf

# dont run openssh-server in chroot environment, debian automatically runs services after installing
mkdir -p $template_dir/etc/ssh
touch $template_dir/etc/ssh/sshd_not_to_be_run

chroot $template_dir apt-get update
chroot $template_dir apt-get -y install ifupdown locales libui-dialog-perl dialog netbase net-tools iproute openssh-server bsdmainutils iputils-ping sudo vim netcat-traditional

# allow ssh to be run on startup
rm $template_dir/etc/ssh/sshd_not_to_be_run

echo "en_US.UTF-8 UTF-8" > $template_dir/etc/locale.gen
chroot $template_dir locale-gen
chroot $template_dir update-locale LANG=en_US.UTF-8

# localtime
cp $template_dir/usr/share/zoneinfo/$(head -n 1 /etc/timezone) $template_dir/etc/localtime

rm $template_dir/bin/sh; ln -s bash $template_dir/bin/sh
chroot $template_dir /usr/sbin/update-rc.d -f umountfs remove
chroot $template_dir /usr/sbin/update-rc.d -f hwclock.sh remove
chroot $template_dir /usr/sbin/update-rc.d -f hwclockfirst.sh remove
chroot $template_dir /usr/sbin/update-rc.d -f mtab.sh remove

chroot $template_dir apt-get clean

# clean log files
>$template_dir/var/log/apt/history.log
>$template_dir/var/log/apt/term.log
>$template_dir/var/log/bootstrap.log
>$template_dir/var/log/dmesg
>$template_dir/var/log/aptitude
>$template_dir/var/log/wtmp
>$template_dir/var/log/btmp

echo "$(date +%F\ %T): Finished: $0 $@"
echo "================================================================================"

exec 1>&3 2>&4
echo "Created template: $name"
