#!/bin/bash

# This script is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

. /etc/simplelxc
# TODO: dont list anything in that directory, maybe "grep -l template- $TEMPLATES_DIR/*/etc/hostname"
ls $TEMPLATES_DIR/
