#!/bin/bash

# This script is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

name=$1
# TODO: check if template with +name is exists
. /etc/simplelxc
# TODO: show a warning about "debian runs any installed servise immediately,
#       don't install services in chroot"
chroot $TEMPLATES_DIR/$name
