#!/bin/bash
from=$1
to=$2
. /etc/simplelxc/config

cp -rap $templates_dir/$from $templates_dir/$to
sed -i "s/template-$from/template-$to/g" $(grep -rl "template-$from" $lxcs_dir/$to/etc/ 2>/dev/null)
