#!/bin/bash
name=${1:-undefined}
# TODO: check if given name is an existing template name
. /etc/simplelxc

if [ "$name" == "undefined" ]; then
	echo "Template name not given"
	exit 2
fi
rm -rf $TEMPLATES_DIR/$name
