#!/bin/bash

# This script is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 2 as
# published by the Free Software Foundation.

name=${1:-undefined}
# TODO: check if given name is an existing template name
. /etc/simplelxc

if [ "$name" == "undefined" ]; then
	echo "Template name not given"
	exit 2
fi
rm -rf --preserve-root $TEMPLATES_DIR/$name
